src/Api/WebSocket/MarketData/BookKeeper.php, src/Command/Command/Market/BookKeeper.php, src/Exception/Api/WebSocket/SocketSequenceException.php
This PR is meant to resolve the following requirements in the resolution for Issue #3:
> - Throw a more specific exception for this scenario
> - Catch exception and correctly re-connect
Tracking of reconnects, and graceful fallback to REST book keeping will require a larger overhaul of the code, and will come in a separate PR.
=> Issue #3 Reconnect on Socket Sequence Error

src/Command/Command/Market/BookKeeper.php, src/Command/Command/Market/Watcher.php, src/Command/Command/Order/BookKeeper.php, src/Command/Command/Order/Placement/Cancel.php, src/Command/Command/Order/Placement/CancelAll.php, src/Command/Command/Order/Placement/NewOrder.php, src/Command/Command/Order/Status/ActiveOrders.php, src/Command/Command/Order/Status/OrderStatus.php
Prefixed all commands with `kobens:gemini` to match a `vendor-name:vendor-package` format.
=> Revised command names

composer.json, src/Exchange.php
++Added docblock to placeOrder and refined the return statement
=> ++Added ext-json and ext-mbstring to composer

src/Api/NonceInterface.php, src/Api/Rest/Response.php, src/Command/Command/TradeRepeater/Archiver.php, src/Command/Command/TradeRepeater/Auditor/BuyPrice.php, src/Command/Command/TradeRepeater/Auditor/SellPrice.php, src/Command/Command/TradeRepeater/Buyer.php, src/Command/Command/TradeRepeater/FillMonitor/Rest.php, src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php, src/Command/Command/TradeRepeater/Seller.php, src/Exception/TradeRepeater/RecordNotFound.php, src/TradeRepeater/Model/Resource/Trade.php, src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php, src/TradeRepeater/Model/Resource/Trade/Action/ActionInterface.php, src/TradeRepeater/Model/Resource/Trade/Action/Archive.php, src/TradeRepeater/Model/Resource/Trade/Action/ArchiveInterface.php, src/TradeRepeater/Model/Resource/Trade/Action/BuyFilled.php, src/TradeRepeater/Model/Resource/Trade/Action/BuyPlaced.php, src/TradeRepeater/Model/Resource/Trade/Action/BuyReady.php, src/TradeRepeater/Model/Resource/Trade/Action/BuySent.php, src/TradeRepeater/Model/Resource/Trade/Action/SellFilled.php, src/TradeRepeater/Model/Resource/Trade/Action/SellPlaced.php, src/TradeRepeater/Model/Resource/Trade/Action/SellSent.php, src/TradeRepeater/Model/Trade.php, src/TradeRepeater/Watcher/TradeSpread.php
Finally implementing a model class surrounding the trade repeater records. Db resource added as well
=> Trade Model

src/Command/Command/Logger/TradeHistory.php
Resolves type error. GitHub issue #39
=> Null default

bin/gemini, env/config.sample.xml, install/db/schema.sql
allows for the throttler to use it's own database.
=> db for throttler

composer.json, composer.lock, src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php, src/Exchange/Currency/Pair.php
- Added support for all trading pairs on the Gemini Exchange.
- Fix issue on `order:new:force-maker` when a trading pair allows for quote price increments of a higher precision than the currency itself even allows (example: LINK/USD).
=> New Trading Pairs Support

.circleci/config.yml, composer.json, composer.lock, genOrder.php, src/TradeRepeater/PricePointGenerator.php, src/TradeRepeater/PricePointGenerator/PricePoint.php, test/Unit/TradeRepeater/PricePointGeneratorDataProvider.php, test/Unit/TradeRepeater/PricePointGeneratorTest.php
=> Support for any PairInterface in  PricePointGenerator

checkOrders.php
The break when the symbol is not matching needed to be a continue statement.
Organized code into functions to reduce declared variables at various points in the execution stack.
=> Fix symbol skipping; organization refactoring

bin/gemini, bootstrap-genorder.php, src/Command/Command/TradeRepeater/Watcher.php, src/TradeRepeater/Watcher/Balances.php, src/TradeRepeater/Watcher/TradeSpread.php
- specify multiple symbols at once to watch
- turn on/off trader data for symbols
- can specify trading pairs to watch price for
=> Many more options added to the watcher

src/Command/Command/TradeRepeater/Buyer.php
=> Use method instead of directly accessing property

bin/gemini, bin/process-watcher, bin/trade-repeater, src/Command/Command/TradeRepeater/CliMonitor/Account.php, src/TradeRepeater/Watcher/Profits.php, src/TradeRepeater/Watcher/TradeSpread.php
- Add total fees
- Sort pairs
- add `ampusd`, `oxtusd`, and `snxusd` to `market:book-keeper` section
- add process watcher cli
=> Reporting Improvements

src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php
=> Catch \Amp\Websocket\ClosedException

src/Command/Command/TradeRepeater/AddToPosition.php, src/TradeRepeater/Model/Resource/Trade.php, src/TradeRepeater/Model/Trade/AddAmount.php
Enhances the existing AddToPosition capability by allowing us to filter by symbol and price range rather than the ID of the database record.
=> TradeRepeater\AddToPosition - Filter by symbol and price range

bin/gemini, src/Command/Command/Info/Pair.php
CLI Command for outputting attribute information on pair(s).
=> CLI Command: Pair Info

src/Command/Command/TradeRepeater/AddToPosition.php
Output summary information when not confirmed for adding to position
=> AddToPosition: Output summary

bin/gemini
Broke it when deleted bootstrap.php in last merge. oops.
=> Fix application initialization

bin/gemini, bin/trade-repeater, src/Command/Command/Logger/TradeHistory.php, src/Command/Command/Market/BookKeeper.php, src/Command/Command/TradeRepeater/Stats/DailyProfit.php, src/Command/Traits/TradeRepeater/ExitProgram.php
Various Tech Debt improvements
- c22477d switch option to argument
- 70fc37e add suffix string option to output
- 6992e32 misc tech tech improvements …
- No more examining the exception thrown, instead we try to select the record to test if it exists or not.
- utilize kill file for ability to target processes of this job type for shutting down
- Ping the database when no results, as we do not want it to hang up on us
- 9d69600 prefer GetIntArg
- 1a13cf1 pass now required adapter to constructor
- eb6438d switch from passing option to passing argument
- 049189a remove unused function
=> Args and logs

bin/book-keepers, bin/gemini, bin/process-watcher, bin/trade-repeater, src/Command/Command/Logger/TradeHistory.php, src/Command/Command/TradeRepeater/AddToPosition.php, src/TradeRepeater/CliMonitor/Balances.php, src/TradeRepeater/CliMonitor/Helper/Data.php, src/TradeRepeater/CliMonitor/Helper/DataInterface.php, src/TradeRepeater/CliMonitor/Profits.php, src/TradeRepeater/Model/Trade/AddAmount.php
- 7964a4c file for starting of strictly book keepers
- 5410122 book keepers removed; trade repeater before logger;sleep between loggers
- 9e904a3 accurate count of processes, clear as part of echo
- 17d1f1c Added to profits table past 24 hours column; Added to account table …
- 544f0fc Correct usage of the $amount variable; Output when a record is skipped
- 3c4dcd7 WIP - this is apparently all borked. just select every time
=> Various cleanups

src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php
=> InvalidNonceException tries again

src/Command/Command/Market/BookKeeper.php
=> Handle ClosedException

src/Api/Rest/PrivateEndpoints/OrderStatus/GetPastTrades.php, src/Command/Command/Logger/TradeHistory.php
=> Handle GatewayTimeoutException

src/Command/Command/Market/BookKeeper.php, src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php
=> handle DnsException

bin/gemini, src/Command/Command/TradeRepeater/Auditor/BuyPrice.php, src/Command/Command/TradeRepeater/Auditor/SellPrice.php, src/Command/Command/TradeRepeater/Buyer.php, src/Command/Command/TradeRepeater/Seller.php, src/Command/Traits/TradeRepeater/DbPing.php
When too much time had passed between placing buy or sell orders the connection to the throttler would hang up on us.
=> Ping connection used for throttling 

src/Command/Command/TradeRepeater/AddToPosition.php, src/TradeRepeater/Model/Trade/AddAmount.php
=> Validate precision, move amount arg to end

src/Api/WebSocket/MarketData/BookKeeper.php, src/Command/Command/Market/BookKeeper.php, src/Command/Traits/Output.php, src/Exception/Api/WebSocket/BookAlreadyOpenException.php
=> improved handling of reopening a book; improved output formatting

src/TradeRepeater/CliMonitor/TradeSpread.php
=> handle when there are no orders

bin/gemini, src/Command/Command/TradeRepeater/CliMonitor/AverageOrderSize.php, src/TradeRepeater/CliMonitor/AverageOrderSize.php
Just a simple tool to check average order amounts
=> Average Order Size

src/Command/Command/TradeRepeater/UsdProfitsDistributor.php, src/TradeRepeater/UsdProfitsDistributor.php, src/TradeRepeater/UsdProfitsDistributorInterface.php
Functional but needs work. Plus I think I already must have committed it
to `bin/gemini` in a prior PR without the supporting classes... oops
=> WIP - USD Profits Distributor

bin/gemini, src/Command/Command/TradeRepeater/CliMonitor/AverageOrderSize.php, src/TradeRepeater/CliMonitor/AverageOrderSize.php, src/TradeRepeater/UsdProfitsDistributor.php, src/TradeRepeater/UsdProfitsDistributor/AllPairs.php, src/TradeRepeater/UsdProfitsDistributor/LeastInvested.php, src/TradeRepeater/UsdProfitsDistributor/RecordSelectorInterface.php, src/TradeRepeater/UsdProfitsDistributor/TopPairs.php, src/TradeRepeater/UsdProfitsDistributor/Traits/Fetch.php
We now will add to the variaous positions based off a few strategies:
- Most popular (by trading activity) trading pairs for the past week
- Least invested trading pair
- All pairs (same as before)
=> USD Profits Distributor - Added Strategies

src/Api/Rest/PrivateEndpoints/OrderStatus/GetActiveOrders.php
=> Handle gateway exceptions

src/Api/Rest/PrivateEndpoints/OrderPlacement/CancelOrder.php
=> Handle exception(s) on cancel order request

bin/gemini, src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php
=> Ping database on heartbeat

src/Command/Command/Logger/TradeHistory.php
=> Handle MaintenanceException; Revise informational output

bin/gemini, src/Command/Command/TradeRepeater/Buyer.php
Need to keep this connection alive for purposes of getPriceByTicker
fixes issue #199
=> Ping public throttler adapter

env/config.sample.xml, install/db/schema.sql, src/Command/Command/Taxes/Form8949.php
- Support for more symbols
- Reports 1099-K Information
- Revised output formatting
- No more symbol selection, report handles all symbols for year
- Ability to store 1099-K info from exchange in environment file and have report output if data in app matches exchange's reporting
=> Taxes Updates

bin/gemini, src/Command/Command/TradeRepeater/Seller.php
=> Ping database to keep connection alive

src/Command/Command/TradeRepeater/Buyer.php
=> call method not removed property

src/Command/Command/TradeRepeater/Buyer.php, src/Command/Command/TradeRepeater/Seller.php
=> Revise output, fix bug
